const FAILURE = "FAILURE";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const RESET =  "RESET";
const LOAD_DATA = "LOAD_DATA";
const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
const START_CLOCK = "START_CLOCK";
const TICK_CLOCK = "TICK_CLOCK";

export const actionTypes = {
  FAILURE,
  INCREMENT,
  DECREMENT,
  RESET,
  LOAD_DATA,
  LOAD_DATA_SUCCESS,
  START_CLOCK,
  TICK_CLOCK,
};
